// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNn9yGXNNgQPcSwMB8iPvbZSyqvqghOpk',
    appId: '1:762160156372:web:c8abff3900b73a36343541',
    messagingSenderId: '762160156372',
    projectId: 'ujicobaapi-53933',
    authDomain: 'ujicobaapi-53933.firebaseapp.com',
    storageBucket: 'ujicobaapi-53933.firebasestorage.app',
    measurementId: 'G-NPV8RV50H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANQ9sPVKN4ZLPMo44lLiSh1bsP15AwUUs',
    appId: '1:762160156372:android:0bd2f4f452d9efea343541',
    messagingSenderId: '762160156372',
    projectId: 'ujicobaapi-53933',
    storageBucket: 'ujicobaapi-53933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8j_m6PacvAZWXdWJdToE71P0v_eyMis4',
    appId: '1:762160156372:ios:8c2de06464dfffde343541',
    messagingSenderId: '762160156372',
    projectId: 'ujicobaapi-53933',
    storageBucket: 'ujicobaapi-53933.firebasestorage.app',
    iosBundleId: 'com.example.ujiCobaApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8j_m6PacvAZWXdWJdToE71P0v_eyMis4',
    appId: '1:762160156372:ios:8c2de06464dfffde343541',
    messagingSenderId: '762160156372',
    projectId: 'ujicobaapi-53933',
    storageBucket: 'ujicobaapi-53933.firebasestorage.app',
    iosBundleId: 'com.example.ujiCobaApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNn9yGXNNgQPcSwMB8iPvbZSyqvqghOpk',
    appId: '1:762160156372:web:338550aed6f3f986343541',
    messagingSenderId: '762160156372',
    projectId: 'ujicobaapi-53933',
    authDomain: 'ujicobaapi-53933.firebaseapp.com',
    storageBucket: 'ujicobaapi-53933.firebasestorage.app',
    measurementId: 'G-FBCZ3ML69B',
  );
}
